<?xml version="1.0"?>
<package format="3">
  <name>turtlebot3_slam_toolbox</name>
  <version>0.1.0</version>
  <description>SLAM Toolbox and RViz configuration for a TurtleBot3 Burger with LDS-03.</description>
  <maintainer email="user@localhost.localdomain">user</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
